{% set version = "0.1.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmlutils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HTMLUtils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HTMLUtils/HTMLUtils_{{ version }}.tar.gz
  sha256: 14e92d45743a9adf21aab726be7d1aacdc901eae443da896b149a657183a8ec4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r2html
  run:
    - r-base
    - r-r2html

test:
  commands:
    - $R -e "library('HTMLUtils')"           # [not win]
    - "\"%R%\" -e \"library('HTMLUtils')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/HTMLUtils/index.html
  license: GPL-2.0-or-later
  summary: Facilitates automated HTML report creation, in particular framed HTML pages and dynamically sortable tables.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
