travis:
  secure:
    BINSTAR_TOKEN: QKM5Ah2SbGLXnUOreCqNCXLANA0Sx7p8/75OgIHb/h8iTlifqgkAoNEe2EFg3i+WOktXZ/Pm2/iVXBiwJLyDCo2kDl9TDajfVBEAeeL2fd3hx425InFJzpsv+yj/DUOXkUQZsAVwfBWyXaodNmjAf7cnc4AWsqJ95QrmLXVrGyv2dg5kYM1kSqASybr/CgOyhsFNo6WvHDEbWYg7KgIx8oeu3Dh/FZn6BGagK/oXBMF+E2fFmVv0EZG1E+CgwEDE27UwLNwxNrkch+Ress9MUohc6TEHFxBILeM1rl8+Fi3+M1HIOMZUTwjL+Zxqc3gWAetLnIWkzVjcw0gWlvEuLBh7W2ckcBCBJ3GP1556tlksRZu0pMZDAqKIzzLCjqU7QYmF8RSVdD0/0K159IEN1s4b6DK5mJkj1KC21dvZdXm20+gm93HyZ7K7CtehYT6ghQs0C6FUp3UBPgT55/rKKZCUyokKRTUh7vTLFJyVSvfHM5d5P1buF3blSFbbg4BJQLN/aTLgJmBFWxhq2SrxI+isoJiGwmjZNG7Zch0HmDoyvbMTTH1LfkjYfPsBsedrSe/p+zI+CD5nGgZcdpTkPNBuK2gawrmnfLB5UJAaaTltdRVCnQM0iMeICmJkcVWRApP0UuaeVDXyUqJb8MV/dyeE0pGom/pS8xIhJ/BQYwQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
