appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: H6YAb8HZ5Y/SmRJ7ZQgB7+2QxeMELpuo+6bcqK/AZ4q0rnmArAMVE7nCNJ1Ll4VCwiP6y5xZa3LJvf+0MlICUzmHOY5V8xEy/VwkJyS3isU6R290OXA+NC2TgB0LMKMxlt7awAfEASx+Z+IDDFwrbvorJJbQJiSRQkuh0TgkT7Lx8As9ixlooiM1RaE9dsBC/iZfuYpp/lfjwdzoCxv/6Br491QKmpDpMXcprur/tdR+RjBj8VxlixkXEQtFbi/mlA2b+e1JjYfBqW+bi51qABOdfH1OM0dLDTN9XPhOT9FA4yOsNCotUuc/dqCnqlwEz4jwXdm5Ad6KR86Cs5TR44SECZJ7Tl7GWx+K9+P8PcqrO6Gr/AUTbNE+3WtGPUIyA3YuuZAaIkHGb4MjMQ+AEbA+1el5MDNhNQTYKq/ooqafkaVjF3a78UO7r7YQZuSMIO9dVV/B+wMlF6i46hKL1eEnaJLKQNT1p0jCSLf8f+Zu3UdrLCObkZqqIeZua6XVHyrgXb8GrtUMPx2Cx9Dkh4Km+LhR96f5XhfOcSGO03JZiwoCb+wvwpW3IfkujJl73uASlc5UTvxTpNNs+D3H/76ifLh+QSfUU42poa3WE6CUqJQ6X5up+eynXbNeJ0yVwWfsXa+GKTXe3NCwkXUwTl170YIdsGEAxTgCVgF0FE4=}
